name: "update-docker-buildx-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.21.4'
permissions:
  contents: read

jobs:
  bump-docker-buildx-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Bump docker-buildx Version
        id: bumpDockerBuildx
        run: |
          echo "OLD_VERSION=$(DEP=docker-buildx make get-dependency-version)" >> $GITHUB_OUTPUT
          make update-docker-buildx-version
          echo "NEW_VERSION=$(DEP=docker-buildx make get-dependency-version)" >> $GITHUB_OUTPUT
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$(git status --porcelain)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create PR
        id: createPR
        if: ${{ steps.bumpDockerBuildx.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'ISO: Update docker-buildx from ${{ steps.bumpDockerBuildx.outputs.OLD_VERSION }} to ${{ steps.bumpDockerBuildx.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_docker_buildx_version
          branch-suffix: short-commit-hash
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'ISO: Update docker-buildx from ${{ steps.bumpDockerBuildx.outputs.OLD_VERSION }} to ${{ steps.bumpDockerBuildx.outputs.NEW_VERSION }}'
          body: |
            The docker-buildx project released a [new version](https://github.com/docker/buildx/releases)

            This PR was auto-generated by `make update-docker-buildx-version` using [update-docker-buildx-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-docker-buildx-version.yml) CI Workflow.
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0
        if: ${{ steps.bumpDockerBuildx.outputs.changes != '' }}
        with:
          github-token: ${{ secrets.MINIKUBE_BOT_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.createPR.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ok-to-build-iso'
            })
